apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app
spec:
  containers:
  - name: app
    image: alpine
    command: ["/bin/sh", "-c", "while true; do echo $(date) >> /mnt/data/date.txt; sleep 10; done"]
    volumeMounts:
    - name: app-volume
      mountPath: /mnt/data
  volumes:
  - name: app-volume
    persistentVolumeClaim:
      claimName: ssd-pvc