apiVersion: v1
kind: Pod
metadata:
  name: nginx-qos-pod
  labels:
    app: nginx-qos
spec:
  containers:
    - name: nginx-qos
      image: nginx:stable
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "300Mi"
          cpu: "200m"
        limits:
          memory: "600Mi"
          cpu: "500m"
    - name: busybox-container
      image: busybox
      command: [
        "sh",
        "-c",
        "sleep 3600"
      ]
      resources:
        requests:
          memory: "100Mi"
          cpu: "50m"
        limits:
          memory: "100Mi"
          cpu: "50m"
