apiVersion: v1
kind: Pod
metadata:
  name: nginx-qos-pod
  labels:
    app: nginx-qos
spec:
  containers:
    - name: nginx-qos
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "500Mi"
          cpu: "500m"
        limits:
          memory: "500Mi"
          cpu: "500m"
