apiVersion: v1
kind: Pod
metadata:
  name: stress-app1
  labels:
    app: stress-app1
spec:
  containers:
    - name: stress-app1
      image: busybox
      command: [
        "sh",
        "-c",
        "sleep 3600"
      ]
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "200Mi"