apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: cm-volume
      mountPath: /config
    - name: secret-volume
      mountPath: /secret-config
  volumes:
    - name: cm-volume
      configMap:
        name: cm1
    - name: secret-volume
      secret:
        secretName: secret1
