apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    command: [
      "sh",
      "-c",
      "echo APP_NAME:$APP_NAME APP_PORT:$APP_PORT"
    ]
    envFrom:
    - configMapRef:
        name: nginx-config  