apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: 4rt1ks0n/myapp
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: db_pass
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: db_user
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: db_user
    - name: DB_HOST
      value: "postgres-service"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000
  type: LoadBalancer