apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:
    spec:
      containers:
      - name: simple-job
        image: alpine
        command: 
          [
            "sh",
            "-c",
            'echo "Data proccessed" && sleep 30'
          ]
      restartPolicy: Never
  backoffLimit: 4
